# home

root:
    path: /
    defaults:
        resource: "landing"
    methods: [GET, POST]
    
admin:
    path: /{resource}/{action}{slash}
    requirements:
        resource: "admin"
        slash: "[/]{0,1}"
    methods: [GET, POST, PUT, DELETE]

    

terms:
    path: /{resource}/{action}{slash}
    requirements:
        resource: "terms"
        slash: "[/]{0,1}"
    methods: [GET, POST, PUT, DELETE]    

    

user:
    path: /{resource}/{action}{slash}
    requirements:
        resource: "user"
        slash: "[/]{0,1}"
    methods: [GET, POST, PUT, DELETE]  

    

pornstar:
    path: /{resource}/{action}{slash}
    requirements:
        resource: "pornstar"
        slash: "[/]{0,1}"
    methods: [GET, POST, PUT, DELETE] 

    

video:
    path: /{resource}/{action}{slash}
    requirements:
        resource: "video"
        slash: "[/]{0,1}"
    methods: [GET, POST, PUT, DELETE] 
 

image:
    path: /{resource}/{action}{slash}
    requirements:
        resource: "image"
        slash: "[/]{0,1}"
    methods: [GET, POST, PUT, DELETE]   
    
statistic:
    path: /{resource}/{action}{slash}
    requirements:
        resource: "statistic"
        slash: "[/]{0,1}"
    methods: [GET, POST, PUT, DELETE] 